apiVersion: apps/v1
kind: Deployment
metadata:
  #name: nginx-deployment-test
  name: nginx-latest
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  #strategy:
    #type: Recreate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        