apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      {{- include "spring.labels" .| nindent 6 }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
       {{- include "spring.labels" .| nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: 8080
