kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.deployment.name }}-svc
spec:
  selector:
    {{- include "spring.labels" .| nindent 4 }}
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
  - name: http
    protocol: TCP
    port:  80
    targetPort: 8080
